import {
  DataSourceMetadata,
  DataSyncLog,
  DataQualityReport,
  DataProvenance,
  TrustLevel,
} from './types';

export const REGISTERED_DATA_SOURCES: DataSourceMetadata[] = [
  {
    id: 'src_cpcb_aqi',
    name: 'National Air Quality Index (NAQI) Real-Time Monitoring Network',
    publisher: 'Central Pollution Control Board (CPCB)',
    parentMinistryOrOrg: 'Ministry of Environment, Forest and Climate Change, Govt of India',
    sourceUrl: 'https://data.gov.in/resource/real-time-air-quality-index-various-monitoring-stations',
    apiUrl: 'https://api.data.gov.in/resource/3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69',
    license: 'Open Government Data License (OGDL) - India',
    licenseUrl: 'https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf',
    category: 'Environment & Climate',
    country: 'India',
    updateFrequency: 'REALTIME',
    lastSuccessfulSync: '2026-08-13T22:30:00+05:30',
    lastChecked: '2026-08-13T22:38:00+05:30',
    status: 'ACTIVE',
    schemaVersion: 'v2.4.1',
    dataQualityScore: 98.4,
    attribution: 'Source: Central Pollution Control Board (CPCB), Govt of India via data.gov.in',
    terms: 'Free public reuse with mandatory attribution to CPCB / data.gov.in',
    geographicCoverage: 'All-India (420+ Continuous Ambient Air Quality Monitoring Stations across 28 States & 8 UTs)',
    timeCoverage: 'Continuous Real-Time (Hourly Aggregation)',
    format: 'JSON / REST',
    recordsTotal: 184520,
  },
  {
    id: 'src_census_pca_2011',
    name: 'Primary Census Abstract (PCA) 2011: District & Sub-District Demographics',
    publisher: 'Office of the Registrar General & Census Commissioner, India',
    parentMinistryOrOrg: 'Ministry of Home Affairs, Government of India',
    sourceUrl: 'https://censusindia.gov.in/census.website/data/census-tables',
    apiUrl: 'https://data.gov.in/resource/district-level-primary-census-abstract-2011',
    license: 'Open Government Data License (OGDL) - India',
    licenseUrl: 'https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf',
    category: 'Demographics & Population',
    country: 'India',
    updateFrequency: 'DECENNIAL',
    lastSuccessfulSync: '2026-08-01T00:00:00+05:30',
    lastChecked: '2026-08-13T12:00:00+05:30',
    status: 'ACTIVE',
    schemaVersion: 'v1.0.0',
    dataQualityScore: 99.8,
    attribution: 'Source: Census of India 2011, Ministry of Home Affairs, Govt of India',
    terms: 'Official aggregate statistical data. Individual household privacy protected.',
    geographicCoverage: 'All 640 Census Districts & 5,924 Sub-Districts/Talukas across India',
    timeCoverage: 'Census Reference Year 2011 (Official Baseline Data)',
    format: 'CSV',
    recordsTotal: 640820,
  },
  {
    id: 'src_morth_roads',
    name: 'Road Infrastructure & Traffic Safety Annual Statistics',
    publisher: 'Ministry of Road Transport and Highways (MoRTH)',
    parentMinistryOrOrg: 'Government of India',
    sourceUrl: 'https://morth.nic.in/road-accidents-in-india',
    apiUrl: 'https://data.gov.in/resource/road-transport-and-highway-statistics',
    license: 'Open Government Data License (OGDL) - India',
    licenseUrl: 'https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf',
    category: 'Transport & Infrastructure',
    country: 'India',
    updateFrequency: 'ANNUAL',
    lastSuccessfulSync: '2026-07-15T04:00:00+05:30',
    lastChecked: '2026-08-13T10:00:00+05:30',
    status: 'ACTIVE',
    schemaVersion: 'v3.1.0',
    dataQualityScore: 96.2,
    attribution: 'Source: Transport Research Wing, MoRTH, Government of India',
    terms: 'Official aggregate statistics on road quality, network density, and blackspots.',
    geographicCoverage: 'National Highways, State Highways & District Roads across India',
    timeCoverage: '2018 – 2025 Annual Series',
    format: 'CSV',
    recordsTotal: 48920,
  },
  {
    id: 'src_cgwb_water',
    name: 'Dynamic Ground Water Resource Assessment of India',
    publisher: 'Central Ground Water Board (CGWB)',
    parentMinistryOrOrg: 'Department of Water Resources, Ministry of Jal Shakti, Govt of India',
    sourceUrl: 'https://cgwb.gov.in/en/ground-water-assessment',
    apiUrl: 'https://data.gov.in/resource/national-ground-water-assessment-tables',
    license: 'Open Government Data License (OGDL) - India',
    licenseUrl: 'https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf',
    category: 'Water Resources & Drought',
    country: 'India',
    updateFrequency: 'ANNUAL',
    lastSuccessfulSync: '2026-06-30T10:00:00+05:30',
    lastChecked: '2026-08-13T15:00:00+05:30',
    status: 'ACTIVE',
    schemaVersion: 'v2.0.0',
    dataQualityScore: 95.7,
    attribution: 'Source: Central Ground Water Board (CGWB), Ministry of Jal Shakti',
    terms: 'Free public reuse for civic research, planning, and groundwater monitoring.',
    geographicCoverage: 'Block / Taluka Level assessment across 7,089 administrative assessment units',
    timeCoverage: '2022 – 2025 National Assessment Cycle',
    format: 'JSON / REST',
    recordsTotal: 35445,
  },
  {
    id: 'src_mohua_sbm',
    name: 'Swachh Bharat Mission Urban (SBM-U) Solid Waste & Sanitation Monitoring',
    publisher: 'Ministry of Housing and Urban Affairs (MoHUA)',
    parentMinistryOrOrg: 'Government of India',
    sourceUrl: 'https://sbmurban.org/progress-data',
    apiUrl: 'https://data.gov.in/resource/swachh-bharat-mission-urban-kpi',
    license: 'Open Government Data License (OGDL) - India',
    licenseUrl: 'https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf',
    category: 'Public Utilities & Sanitation',
    country: 'India',
    updateFrequency: 'MONTHLY',
    lastSuccessfulSync: '2026-08-01T06:00:00+05:30',
    lastChecked: '2026-08-13T18:00:00+05:30',
    status: 'ACTIVE',
    schemaVersion: 'v2.2.0',
    dataQualityScore: 97.1,
    attribution: 'Source: Ministry of Housing and Urban Affairs (MoHUA), Govt of India',
    terms: 'Urban Local Body (ULB) waste processing, door-to-door collection, and ODF+ data.',
    geographicCoverage: '4,800+ Statutory Urban Local Bodies (Municipal Corporations & Municipalities)',
    timeCoverage: '2019 – Present (Monthly updates)',
    format: 'JSON / REST',
    recordsTotal: 115200,
  },
  {
    id: 'src_osm_boundaries',
    name: 'OpenStreetMap India Geographic Boundaries & Road Network',
    publisher: 'OpenStreetMap Foundation & Community Contributors',
    parentMinistryOrOrg: 'Open-Source Geospatial Community',
    sourceUrl: 'https://www.openstreetmap.org',
    apiUrl: 'https://overpass-api.de/api/interpreter',
    license: 'Open Database License (ODbL) 1.0',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    category: 'Geographic Boundaries & Maps',
    country: 'India',
    updateFrequency: 'WEEKLY',
    lastSuccessfulSync: '2026-08-10T02:00:00+05:30',
    lastChecked: '2026-08-13T21:00:00+05:30',
    status: 'ACTIVE',
    schemaVersion: 'v1.6.0',
    dataQualityScore: 99.1,
    attribution: 'Map data &copy; OpenStreetMap contributors, licensed under ODbL',
    terms: 'Open Database License. Mandatory attribution "© OpenStreetMap contributors".',
    geographicCoverage: 'All-India State, District, City, Ward Boundaries and Road Polylines',
    timeCoverage: 'Continuous Community Mapping',
    format: 'GeoJSON',
    recordsTotal: 842000,
  },
  {
    id: 'src_janvaani_citizen',
    name: 'JanVaani Citizen Problem & Co-Created Solution Registry',
    publisher: 'JanVaani Civic Intelligence Platform',
    parentMinistryOrOrg: 'JanVaani Open Citizen Data Network',
    sourceUrl: 'https://janvaani.in/problems',
    license: 'Creative Commons Attribution-NonCommercial 4.0 (CC BY-NC 4.0)',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc/4.0/',
    category: 'Citizen Reports & Solutions',
    country: 'India',
    updateFrequency: 'REALTIME',
    lastSuccessfulSync: '2026-08-13T22:38:00+05:30',
    lastChecked: '2026-08-13T22:38:00+05:30',
    status: 'ACTIVE',
    schemaVersion: 'v2.5.0',
    dataQualityScore: 96.8,
    attribution: 'JanVaani Citizen Problem Intelligence Platform (Proof-of-Impact Verified)',
    terms: 'Crowdsourced citizen reports with multi-factor proof verification and GPS differential fuzzing.',
    geographicCoverage: 'Citizen Reports across Vadodara, Ahmedabad, Surat, Mumbai, Bengaluru, Delhi NCR',
    timeCoverage: 'Live Platform Stream (2025 – Present)',
    format: 'JSON / REST',
    recordsTotal: 12642,
  },
];

export const LATEST_SYNC_LOGS: DataSyncLog[] = [
  {
    id: 'log_sync_cpcb_0813',
    sourceId: 'src_cpcb_aqi',
    sourceName: 'CPCB Real-Time National Air Quality Index',
    startedAt: '2026-08-13T22:29:45+05:30',
    completedAt: '2026-08-13T22:30:12+05:30',
    recordsReceived: 428,
    recordsInserted: 428,
    recordsUpdated: 0,
    recordsRejected: 0,
    errors: [],
    status: 'SUCCESS',
    durationMs: 27000,
  },
  {
    id: 'log_sync_janvaani_0813',
    sourceId: 'src_janvaani_citizen',
    sourceName: 'JanVaani Citizen Problem Ingestion Stream',
    startedAt: '2026-08-13T22:37:50+05:30',
    completedAt: '2026-08-13T22:38:02+05:30',
    recordsReceived: 14,
    recordsInserted: 14,
    recordsUpdated: 2,
    recordsRejected: 0,
    errors: [],
    status: 'SUCCESS',
    durationMs: 12000,
  },
  {
    id: 'log_sync_osm_0810',
    sourceId: 'src_osm_boundaries',
    sourceName: 'OpenStreetMap Administrative Boundary Vectors',
    startedAt: '2026-08-10T01:55:00+05:30',
    completedAt: '2026-08-10T02:00:15+05:30',
    recordsReceived: 8420,
    recordsInserted: 120,
    recordsUpdated: 8300,
    recordsRejected: 0,
    errors: [],
    status: 'SUCCESS',
    durationMs: 315000,
  },
  {
    id: 'log_sync_sbm_0801',
    sourceId: 'src_mohua_sbm',
    sourceName: 'MoHUA Swachh Bharat Urban Monthly Digest',
    startedAt: '2026-08-01T05:50:00+05:30',
    completedAt: '2026-08-01T06:00:10+05:30',
    recordsReceived: 4820,
    recordsInserted: 4820,
    recordsUpdated: 0,
    recordsRejected: 0,
    errors: [],
    status: 'SUCCESS',
    durationMs: 610000,
  },
];

export const LATEST_QUALITY_REPORTS: DataQualityReport[] = [
  {
    id: 'dq_cpcb_0813',
    sourceId: 'src_cpcb_aqi',
    timestamp: '2026-08-13T22:30:15+05:30',
    nullViolations: 0,
    coordinateViolations: 0,
    duplicateCount: 0,
    outOfRangeValues: 0,
    schemaValid: true,
    overallScore: 98.4,
    status: 'PASS',
    notes: [
      'All 428 CAAQMS station telemetry packets validated against CPCB range bounds (0 - 500 AQI).',
      'Geographic coordinate bounds verified within Indian territorial polygon.',
    ],
  },
  {
    id: 'dq_census_0801',
    sourceId: 'src_census_pca_2011',
    timestamp: '2026-08-01T00:05:00+05:30',
    nullViolations: 0,
    coordinateViolations: 0,
    duplicateCount: 0,
    outOfRangeValues: 0,
    schemaValid: true,
    overallScore: 99.8,
    status: 'PASS',
    notes: [
      'Census demographic aggregates verified against Registrar General official district totals.',
      'Data minimization & privacy check passed (zero individual PII fields present).',
    ],
  },
  {
    id: 'dq_janvaani_0813',
    sourceId: 'src_janvaani_citizen',
    timestamp: '2026-08-13T22:38:05+05:30',
    nullViolations: 0,
    coordinateViolations: 0,
    duplicateCount: 1, // Auto-detected duplicate flagged for merging
    outOfRangeValues: 0,
    schemaValid: true,
    overallScore: 96.8,
    status: 'PASS',
    notes: [
      'GPS differential privacy check applied to public coordinates.',
      'EXIF metadata stripping and AI face/number plate blurring verified on uploaded media.',
    ],
  },
];

// Helper to look up provenance for any dataset or KPI
export function getProvenanceForSource(sourceId: string): DataProvenance {
  const meta = REGISTERED_DATA_SOURCES.find((s) => s.id === sourceId);
  if (!meta) {
    return {
      sourceId: 'unknown',
      datasetName: 'Unregistered Dataset',
      publisher: 'Unknown Publisher',
      retrievalTimestamp: new Date().toISOString(),
      freshness: 'UNKNOWN',
      license: 'Unknown',
      sourceUrl: 'https://data.gov.in',
      trustLevel: 'DEMO_DATA',
    };
  }

  const trustLevel: TrustLevel =
    sourceId === 'src_janvaani_citizen'
      ? 'CITIZEN_REPORTED'
      : sourceId === 'src_census_pca_2011'
      ? 'CENSUS_OF_INDIA'
      : sourceId === 'src_osm_boundaries'
      ? 'OPENSTREETMAP'
      : 'OFFICIAL_GOV_DATA';

  return {
    sourceId: meta.id,
    datasetName: meta.name,
    publisher: meta.publisher,
    publishedDate: meta.lastSuccessfulSync,
    retrievalTimestamp: meta.lastSuccessfulSync,
    freshness:
      meta.updateFrequency === 'REALTIME'
        ? 'LIVE'
        : meta.updateFrequency === 'DECENNIAL'
        ? 'HISTORICAL_CENSUS'
        : meta.updateFrequency === 'ANNUAL'
        ? 'ANNUAL_OFFICIAL'
        : 'UPDATED_THIS_MONTH',
    license: meta.license,
    sourceUrl: meta.sourceUrl,
    trustLevel,
    methodologyNotes: meta.terms,
  };
}
