export type LanguageCategory =
  | 'indian_official'
  | 'indian_regional'
  | 'global_popular'
  | 'global_asia'
  | 'global_europe'
  | 'global_americas'
  | 'global_africa'
  | 'global_middle_east'
  | 'global_oceania';

export interface LanguageItem {
  code: string;
  name: string;
  nativeName: string;
  region: string;
  category: LanguageCategory;
  flag: string;
  direction?: 'ltr' | 'rtl';
  isIndian?: boolean;
  isSchedule8?: boolean;
}

export const ALL_LANGUAGES: LanguageItem[] = [
  // ==========================================
  // 🇮🇳 ALL 22 OFFICIAL 8TH SCHEDULE INDIAN LANGUAGES
  // ==========================================
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    region: 'India (National)',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'en-in',
    name: 'English (India)',
    nativeName: 'English (India)',
    region: 'India / Official',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    region: 'West Bengal, Tripura, Assam',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    region: 'Maharashtra, Goa',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    region: 'Andhra Pradesh, Telangana',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    region: 'Tamil Nadu, Puducherry',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    region: 'Gujarat, Daman & Diu',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    region: 'India (National), Telangana, UP, J&K',
    category: 'indian_official',
    flag: '🇮🇳',
    direction: 'rtl',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    region: 'Karnataka',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    region: 'Kerala, Lakshadweep',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    region: 'Odisha',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    region: 'Punjab, Haryana, Delhi',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    region: 'Assam',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    region: 'Bihar, Jharkhand',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'sat',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    region: 'Jharkhand, Odisha, West Bengal',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'کٲشُر / कॉशुर',
    region: 'Jammu & Kashmir',
    category: 'indian_official',
    flag: '🇮🇳',
    direction: 'rtl',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    region: 'Sikkim, West Bengal, Nepal',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'kok',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    region: 'Goa, Maharashtra, Karnataka',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'sd',
    name: 'Sindhi',
    nativeName: 'سنڌي / सिन्धी',
    region: 'Gujarat, Maharashtra, Rajasthan',
    category: 'indian_official',
    flag: '🇮🇳',
    direction: 'rtl',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'doi',
    name: 'Dogri',
    nativeName: 'डोगरी',
    region: 'Jammu & Kashmir, Himachal Pradesh',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'mni',
    name: 'Manipuri (Meitei)',
    nativeName: 'মৈতৈলোন্ / ꯃꯤꯇꯩꯂꯣꯟ',
    region: 'Manipur',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'brx',
    name: 'Bodo',
    nativeName: 'बर’',
    region: 'Assam, Bodoland',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    region: 'India (Classical)',
    category: 'indian_official',
    flag: '🇮🇳',
    isIndian: true,
    isSchedule8: true,
  },

  // ==========================================
  // 🇮🇳 MAJOR INDIAN REGIONAL LANGUAGES & DIALECTS
  // ==========================================
  {
    code: 'bho',
    name: 'Bhojpuri',
    nativeName: 'भोजपुरी',
    region: 'Bihar, UP, Jharkhand',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'mwr',
    name: 'Marwari / Rajasthani',
    nativeName: 'मारवाड़ी / राजस्थानी',
    region: 'Rajasthan, Gujarat',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'hne',
    name: 'Chhattisgarhi',
    nativeName: 'छत्तीसगढ़ी',
    region: 'Chhattisgarh',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'mag',
    name: 'Magahi',
    nativeName: 'मगही',
    region: 'Bihar, Jharkhand',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'bgc',
    name: 'Haryanvi',
    nativeName: 'हरियाणवी',
    region: 'Haryana, Delhi',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'tcy',
    name: 'Tulu',
    nativeName: 'ತುಳು',
    region: 'Karnataka (Coastal), Kerala',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'gbm',
    name: 'Garhwali',
    nativeName: 'गढ़वळि',
    region: 'Uttarakhand',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'kfy',
    name: 'Kumaoni',
    nativeName: 'कुमाऊँनी',
    region: 'Uttarakhand',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'lus',
    name: 'Mizo',
    nativeName: 'Mizo ṭawng',
    region: 'Mizoram',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'kha',
    name: 'Khasi',
    nativeName: 'Ka Ktien Khasi',
    region: 'Meghalaya',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'grt',
    name: 'Garo',
    nativeName: 'A·chik',
    region: 'Meghalaya, Assam',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'lep',
    name: 'Lepcha',
    nativeName: 'Róng ríng',
    region: 'Sikkim, West Bengal',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'gon',
    name: 'Gondi',
    nativeName: 'गोंडी / கோண்டி',
    region: 'Madhya Pradesh, Maharashtra, Chhattisgarh',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },
  {
    code: 'bhb',
    name: 'Bhili',
    nativeName: 'भीली',
    region: 'Rajasthan, Gujarat, MP',
    category: 'indian_regional',
    flag: '🇮🇳',
    isIndian: true,
  },

  // ==========================================
  // 🌍 100+ GLOBAL COUNTRY / INTERNATIONAL LANGUAGES
  // ==========================================

  // --- POPULAR GLOBAL & UN OFFICIAL ---
  {
    code: 'en',
    name: 'English (US/UK/Global)',
    nativeName: 'English',
    region: 'Global / United States / UK',
    category: 'global_popular',
    flag: '🌐',
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    region: 'Spain, Mexico, Latin America (20+ countries)',
    category: 'global_popular',
    flag: '🇪🇸',
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    region: 'France, Canada, Francophonie (29 countries)',
    category: 'global_popular',
    flag: '🇫🇷',
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    region: 'Germany, Austria, Switzerland',
    category: 'global_popular',
    flag: '🇩🇪',
  },
  {
    code: 'zh-cn',
    name: 'Chinese (Simplified)',
    nativeName: '简体中文',
    region: 'China, Singapore',
    category: 'global_popular',
    flag: '🇨🇳',
  },
  {
    code: 'zh-tw',
    name: 'Chinese (Traditional)',
    nativeName: '繁體中文',
    region: 'Taiwan, Hong Kong, Macau',
    category: 'global_popular',
    flag: '🇹🇼',
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    region: 'Middle East & North Africa (22 countries)',
    category: 'global_popular',
    flag: '🇸🇦',
    direction: 'rtl',
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    region: 'Russia, CIS countries',
    category: 'global_popular',
    flag: '🇷🇺',
  },
  {
    code: 'pt',
    name: 'Portuguese (Global & Brazil)',
    nativeName: 'Português',
    region: 'Brazil, Portugal, Angola, Mozambique',
    category: 'global_popular',
    flag: '🇧🇷',
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    region: 'Japan',
    category: 'global_popular',
    flag: '🇯🇵',
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    region: 'South Korea, North Korea',
    category: 'global_popular',
    flag: '🇰🇷',
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    region: 'Indonesia',
    category: 'global_popular',
    flag: '🇮🇩',
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    region: 'Turkey, Cyprus',
    category: 'global_popular',
    flag: '🇹🇷',
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    region: 'Italy, Switzerland, San Marino',
    category: 'global_popular',
    flag: '🇮🇹',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    region: 'Vietnam',
    category: 'global_popular',
    flag: '🇻🇳',
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    region: 'Thailand',
    category: 'global_popular',
    flag: '🇹🇭',
  },
  {
    code: 'fa',
    name: 'Persian (Farsi)',
    nativeName: 'فارسی',
    region: 'Iran, Afghanistan, Tajikistan',
    category: 'global_popular',
    flag: '🇮🇷',
    direction: 'rtl',
  },
  {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    region: 'Poland',
    category: 'global_popular',
    flag: '🇵🇱',
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    region: 'Ukraine',
    category: 'global_popular',
    flag: '🇺🇦',
  },
  {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    region: 'Netherlands, Belgium, Suriname',
    category: 'global_popular',
    flag: '🇳🇱',
  },

  // --- ASIA & PACIFIC ---
  {
    code: 'ms',
    name: 'Malay',
    nativeName: 'Bahasa Melayu',
    region: 'Malaysia, Brunei, Singapore',
    category: 'global_asia',
    flag: '🇲🇾',
  },
  {
    code: 'tl',
    name: 'Tagalog (Filipino)',
    nativeName: 'Wikang Filipino',
    region: 'Philippines',
    category: 'global_asia',
    flag: '🇵🇭',
  },
  {
    code: 'my',
    name: 'Burmese',
    nativeName: 'မြန်မာဘာသာ',
    region: 'Myanmar',
    category: 'global_asia',
    flag: '🇲🇲',
  },
  {
    code: 'km',
    name: 'Khmer',
    nativeName: 'ភាសាខ្មែរ',
    region: 'Cambodia',
    category: 'global_asia',
    flag: '🇰🇭',
  },
  {
    code: 'lo',
    name: 'Lao',
    nativeName: 'ພາສາລາວ',
    region: 'Laos',
    category: 'global_asia',
    flag: '🇱🇦',
  },
  {
    code: 'si',
    name: 'Sinhala',
    nativeName: 'සිංහල',
    region: 'Sri Lanka',
    category: 'global_asia',
    flag: '🇱🇰',
  },
  {
    code: 'dz',
    name: 'Dzongkha',
    nativeName: 'རྫོང་ཁ',
    region: 'Bhutan',
    category: 'global_asia',
    flag: '🇧🇹',
  },
  {
    code: 'bo',
    name: 'Tibetan',
    nativeName: 'བོད་སྐད',
    region: 'Tibet / Himalayas',
    category: 'global_asia',
    flag: '🏔️',
  },
  {
    code: 'mn',
    name: 'Mongolian',
    nativeName: 'Монгол хэл',
    region: 'Mongolia',
    category: 'global_asia',
    flag: '🇲🇳',
  },
  {
    code: 'kk',
    name: 'Kazakh',
    nativeName: 'Қазақ тілі',
    region: 'Kazakhstan',
    category: 'global_asia',
    flag: '🇰🇿',
  },
  {
    code: 'uz',
    name: 'Uzbek',
    nativeName: "O'zbek tili",
    region: 'Uzbekistan',
    category: 'global_asia',
    flag: '🇺🇿',
  },
  {
    code: 'tg',
    name: 'Tajik',
    nativeName: 'Тоҷикӣ',
    region: 'Tajikistan',
    category: 'global_asia',
    flag: '🇹🇯',
  },
  {
    code: 'ky',
    name: 'Kyrgyz',
    nativeName: 'Кыргызча',
    region: 'Kyrgyzstan',
    category: 'global_asia',
    flag: '🇰🇬',
  },
  {
    code: 'tk',
    name: 'Turkmen',
    nativeName: 'Türkmen dili',
    region: 'Turkmenistan',
    category: 'global_asia',
    flag: '🇹🇲',
  },
  {
    code: 'ps',
    name: 'Pashto',
    nativeName: 'پښتو',
    region: 'Afghanistan, Pakistan',
    category: 'global_asia',
    flag: '🇦🇫',
    direction: 'rtl',
  },
  {
    code: 'ka',
    name: 'Georgian',
    nativeName: 'ქართული',
    region: 'Georgia',
    category: 'global_asia',
    flag: '🇬🇪',
  },
  {
    code: 'hy',
    name: 'Armenian',
    nativeName: 'Հայերեն',
    region: 'Armenia',
    category: 'global_asia',
    flag: '🇦🇲',
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    nativeName: 'Azərbaycan dili',
    region: 'Azerbaijan',
    category: 'global_asia',
    flag: '🇦🇿',
  },
  {
    code: 'dv',
    name: 'Dhivehi (Maldivian)',
    nativeName: 'ދިވެހި',
    region: 'Maldives',
    category: 'global_asia',
    flag: '🇲🇻',
    direction: 'rtl',
  },

  // --- MIDDLE EAST & NORTH AFRICA ---
  {
    code: 'he',
    name: 'Hebrew',
    nativeName: 'עברית',
    region: 'Israel',
    category: 'global_middle_east',
    flag: '🇮🇱',
    direction: 'rtl',
  },
  {
    code: 'ku',
    name: 'Kurdish',
    nativeName: 'Kurdî / کوردی',
    region: 'Kurdistan / Iraq / Syria / Turkey',
    category: 'global_middle_east',
    flag: '☀️',
  },

  // --- EUROPE ---
  {
    code: 'el',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    region: 'Greece, Cyprus',
    category: 'global_europe',
    flag: '🇬🇷',
  },
  {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    region: 'Sweden, Finland',
    category: 'global_europe',
    flag: '🇸🇪',
  },
  {
    code: 'no',
    name: 'Norwegian',
    nativeName: 'Norsk',
    region: 'Norway',
    category: 'global_europe',
    flag: '🇳🇴',
  },
  {
    code: 'da',
    name: 'Danish',
    nativeName: 'Dansk',
    region: 'Denmark, Greenland',
    category: 'global_europe',
    flag: '🇩🇰',
  },
  {
    code: 'fi',
    name: 'Finnish',
    nativeName: 'Suomi',
    region: 'Finland',
    category: 'global_europe',
    flag: '🇫🇮',
  },
  {
    code: 'cs',
    name: 'Czech',
    nativeName: 'Čeština',
    region: 'Czech Republic',
    category: 'global_europe',
    flag: '🇨🇿',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    nativeName: 'Magyar',
    region: 'Hungary',
    category: 'global_europe',
    flag: '🇭🇺',
  },
  {
    code: 'ro',
    name: 'Romanian',
    nativeName: 'Română',
    region: 'Romania, Moldova',
    category: 'global_europe',
    flag: '🇷🇴',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    nativeName: 'Български',
    region: 'Bulgaria',
    category: 'global_europe',
    flag: '🇧🇬',
  },
  {
    code: 'sr',
    name: 'Serbian',
    nativeName: 'Српски / Srpski',
    region: 'Serbia, Bosnia & Herzegovina',
    category: 'global_europe',
    flag: '🇷🇸',
  },
  {
    code: 'hr',
    name: 'Croatian',
    nativeName: 'Hrvatski',
    region: 'Croatia, Bosnia & Herzegovina',
    category: 'global_europe',
    flag: '🇭🇷',
  },
  {
    code: 'bs',
    name: 'Bosnian',
    nativeName: 'Bosanski',
    region: 'Bosnia & Herzegovina',
    category: 'global_europe',
    flag: '🇧🇦',
  },
  {
    code: 'sk',
    name: 'Slovak',
    nativeName: 'Slovenčina',
    region: 'Slovakia',
    category: 'global_europe',
    flag: '🇸🇰',
  },
  {
    code: 'sl',
    name: 'Slovenian',
    nativeName: 'Slovenščina',
    region: 'Slovenia',
    category: 'global_europe',
    flag: '🇸🇮',
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    nativeName: 'Lietuvių kalba',
    region: 'Lithuania',
    category: 'global_europe',
    flag: '🇱🇹',
  },
  {
    code: 'lv',
    name: 'Latvian',
    nativeName: 'Latviešu valoda',
    region: 'Latvia',
    category: 'global_europe',
    flag: '🇱🇻',
  },
  {
    code: 'et',
    name: 'Estonian',
    nativeName: 'Eesti keel',
    region: 'Estonia',
    category: 'global_europe',
    flag: '🇪🇪',
  },
  {
    code: 'is',
    name: 'Icelandic',
    nativeName: 'Íslenska',
    region: 'Iceland',
    category: 'global_europe',
    flag: '🇮🇸',
  },
  {
    code: 'ga',
    name: 'Irish (Gaeilge)',
    nativeName: 'Gaeilge',
    region: 'Ireland',
    category: 'global_europe',
    flag: '🇮🇪',
  },
  {
    code: 'cy',
    name: 'Welsh',
    nativeName: 'Cymraeg',
    region: 'Wales, UK',
    category: 'global_europe',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  },
  {
    code: 'gd',
    name: 'Scottish Gaelic',
    nativeName: 'Gàidhlig',
    region: 'Scotland, UK',
    category: 'global_europe',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  },
  {
    code: 'eu',
    name: 'Basque',
    nativeName: 'Euskara',
    region: 'Basque Country, Spain & France',
    category: 'global_europe',
    flag: '🇪🇸',
  },
  {
    code: 'ca',
    name: 'Catalan',
    nativeName: 'Català',
    region: 'Catalonia, Andorra, Valencia',
    category: 'global_europe',
    flag: '🇪🇸',
  },
  {
    code: 'gl',
    name: 'Galician',
    nativeName: 'Galego',
    region: 'Galicia, Spain',
    category: 'global_europe',
    flag: '🇪🇸',
  },
  {
    code: 'sq',
    name: 'Albanian',
    nativeName: 'Shqip',
    region: 'Albania, Kosovo, North Macedonia',
    category: 'global_europe',
    flag: '🇦🇱',
  },
  {
    code: 'mk',
    name: 'Macedonian',
    nativeName: 'Македонски',
    region: 'North Macedonia',
    category: 'global_europe',
    flag: '🇲🇰',
  },
  {
    code: 'mt',
    name: 'Maltese',
    nativeName: 'Malti',
    region: 'Malta',
    category: 'global_europe',
    flag: '🇲🇹',
  },
  {
    code: 'be',
    name: 'Belarusian',
    nativeName: 'Беларуская',
    region: 'Belarus',
    category: 'global_europe',
    flag: '🇧🇾',
  },
  {
    code: 'lb',
    name: 'Luxembourgish',
    nativeName: 'Lëtzebuergesch',
    region: 'Luxembourg',
    category: 'global_europe',
    flag: '🇱🇺',
  },

  // --- AFRICA ---
  {
    code: 'sw',
    name: 'Swahili',
    nativeName: 'Kiswahili',
    region: 'Kenya, Tanzania, Uganda, East Africa',
    category: 'global_africa',
    flag: '🇹🇿',
  },
  {
    code: 'am',
    name: 'Amharic',
    nativeName: 'አማርኛ',
    region: 'Ethiopia',
    category: 'global_africa',
    flag: '🇪🇹',
  },
  {
    code: 'yo',
    name: 'Yoruba',
    nativeName: 'Èdè Yorùbá',
    region: 'Nigeria, Benin',
    category: 'global_africa',
    flag: '🇳🇬',
  },
  {
    code: 'ha',
    name: 'Hausa',
    nativeName: 'Harshen Hausa',
    region: 'Nigeria, Niger, West Africa',
    category: 'global_africa',
    flag: '🇳🇬',
  },
  {
    code: 'ig',
    name: 'Igbo',
    nativeName: 'Asụsụ Igbo',
    region: 'Nigeria',
    category: 'global_africa',
    flag: '🇳🇬',
  },
  {
    code: 'zu',
    name: 'Zulu',
    nativeName: 'isiZulu',
    region: 'South Africa',
    category: 'global_africa',
    flag: '🇿🇦',
  },
  {
    code: 'xh',
    name: 'Xhosa',
    nativeName: 'isiXhosa',
    region: 'South Africa',
    category: 'global_africa',
    flag: '🇿🇦',
  },
  {
    code: 'af',
    name: 'Afrikaans',
    nativeName: 'Afrikaans',
    region: 'South Africa, Namibia',
    category: 'global_africa',
    flag: '🇿🇦',
  },
  {
    code: 'so',
    name: 'Somali',
    nativeName: 'Af-Soomaali',
    region: 'Somalia, Djibouti, Ethiopia',
    category: 'global_africa',
    flag: '🇸🇴',
  },
  {
    code: 'mg',
    name: 'Malagasy',
    nativeName: 'Fiteny Malagasy',
    region: 'Madagascar',
    category: 'global_africa',
    flag: '🇲🇬',
  },
  {
    code: 'rw',
    name: 'Kinyarwanda',
    nativeName: 'Ikinyarwanda',
    region: 'Rwanda, Uganda, DRC',
    category: 'global_africa',
    flag: '🇷🇼',
  },
  {
    code: 'sn',
    name: 'Shona',
    nativeName: 'chiShona',
    region: 'Zimbabwe, Mozambique',
    category: 'global_africa',
    flag: '🇿🇼',
  },
  {
    code: 'st',
    name: 'Sesotho',
    nativeName: 'Sesotho',
    region: 'Lesotho, South Africa',
    category: 'global_africa',
    flag: '🇱🇸',
  },
  {
    code: 'ny',
    name: 'Chichewa',
    nativeName: 'ChiCheŵa',
    region: 'Malawi, Zambia, Mozambique',
    category: 'global_africa',
    flag: '🇲🇼',
  },
  {
    code: 'ti',
    name: 'Tigrinya',
    nativeName: 'ትግርኛ',
    region: 'Eritrea, Ethiopia',
    category: 'global_africa',
    flag: '🇪🇷',
  },
  {
    code: 'om',
    name: 'Oromo',
    nativeName: 'Afaan Oromoo',
    region: 'Ethiopia, Kenya',
    category: 'global_africa',
    flag: '🇪🇹',
  },

  // --- AMERICAS (INDIGENOUS & CREOLES) ---
  {
    code: 'qu',
    name: 'Quechua',
    nativeName: 'Runasimi',
    region: 'Peru, Bolivia, Ecuador (Andes)',
    category: 'global_americas',
    flag: '🇵🇪',
  },
  {
    code: 'ay',
    name: 'Aymara',
    nativeName: 'Aymar aru',
    region: 'Bolivia, Peru, Chile',
    category: 'global_americas',
    flag: '🇧🇴',
  },
  {
    code: 'gn',
    name: 'Guarani',
    nativeName: "Avañe'ẽ",
    region: 'Paraguay, Argentina, Bolivia',
    category: 'global_americas',
    flag: '🇵🇾',
  },
  {
    code: 'ht',
    name: 'Haitian Creole',
    nativeName: 'Kreyòl Ayisyen',
    region: 'Haiti, Caribbean',
    category: 'global_americas',
    flag: '🇭🇹',
  },
  {
    code: 'nah',
    name: 'Nahuatl',
    nativeName: 'Nāhuatlahtōlli',
    region: 'Mexico',
    category: 'global_americas',
    flag: '🇲🇽',
  },
  {
    code: 'iu',
    name: 'Inuktitut',
    nativeName: 'ᐃᓄᒃᑎᑐᑦ',
    region: 'Canada (Nunavut / Arctic)',
    category: 'global_americas',
    flag: '🇨🇦',
  },

  // --- OCEANIA ---
  {
    code: 'mi',
    name: 'Māori',
    nativeName: 'Te Reo Māori',
    region: 'New Zealand',
    category: 'global_oceania',
    flag: '🇳🇿',
  },
  {
    code: 'sm',
    name: 'Samoan',
    nativeName: "Gagana fa'a Sāmoa",
    region: 'Samoa, American Samoa',
    category: 'global_oceania',
    flag: '🇼🇸',
  },
  {
    code: 'to',
    name: 'Tongan',
    nativeName: 'Lea Faka-Tonga',
    region: 'Tonga',
    category: 'global_oceania',
    flag: '🇹🇴',
  },
  {
    code: 'fj',
    name: 'Fijian',
    nativeName: 'Na Vosa Vakaviti',
    region: 'Fiji',
    category: 'global_oceania',
    flag: '🇫🇯',
  },
  {
    code: 'tpi',
    name: 'Tok Pisin',
    nativeName: 'Tok Pisin',
    region: 'Papua New Guinea',
    category: 'global_oceania',
    flag: '🇵🇬',
  },
  {
    code: 'haw',
    name: 'Hawaiian',
    nativeName: 'ʻŌlelo Hawaiʻi',
    region: 'Hawaii, USA',
    category: 'global_oceania',
    flag: '🌺',
  },
];

export const POPULAR_INDIAN_LANGUAGES = ALL_LANGUAGES.filter(
  (l) => l.isIndian && l.isSchedule8
);

export const ALL_INDIAN_LANGUAGES = ALL_LANGUAGES.filter((l) => l.isIndian);

export const GLOBAL_LANGUAGES = ALL_LANGUAGES.filter((l) => !l.isIndian);

export function getLanguageByCode(code: string): LanguageItem {
  const found = ALL_LANGUAGES.find(
    (l) => l.code.toLowerCase() === code.toLowerCase()
  );
  if (found) return found;
  return ALL_LANGUAGES[0]; // fallback English
}
