import {
  ProblemCase,
  Solution,
  Community,
  Bounty,
  TopContributor,
  CivicBadge,
  ResearchDataset,
  GovernmentDepartment,
  PolicyInsightItem,
  AuditLogItem,
  User,
} from './types';

export const CURRENT_USER: User = {
  id: 'usr_001',
  name: 'Neha Sharma',
  email: 'neha.sharma@example.com',
  phone: '+91 98765 43210',
  role: 'citizen',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  location: 'Karelibaug, Vadodara, Gujarat',
  bio: 'Civic tech enthusiast, active community validator & urban sustainability advocate.',
  points: 4680,
  badgesCount: 12,
  level: 12,
  levelTitle: 'Civic Champion',
  verified: true,
  joinedDate: 'Jan 2025',
};

export const DEMO_USERS: Record<string, User> = {
  citizen: CURRENT_USER,
  student: {
    id: 'usr_student',
    name: 'Aarav Joshi',
    email: 'aarav.j@iit.ac.in',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    location: 'Ahmedabad, Gujarat',
    bio: 'Civil Engineering Student @ IIT. Building cost-effective drainage solutions.',
    points: 2450,
    badgesCount: 7,
    level: 8,
    levelTitle: 'Solution Innovator',
    verified: true,
    joinedDate: 'Mar 2025',
  },
  expert: {
    id: 'usr_expert',
    name: 'Dr. Vikram Shah',
    email: 'vikram.urban@ai.org',
    role: 'expert',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    location: 'Mumbai, Maharashtra',
    bio: 'Senior Urban Infrastructure Planner with 18+ years consulting Indian Smart Cities.',
    points: 5890,
    badgesCount: 15,
    level: 15,
    levelTitle: 'Senior Civic Architect',
    verified: true,
    joinedDate: 'Nov 2024',
  },
  officer: {
    id: 'usr_officer',
    name: 'Rajesh K. Patel',
    email: 'r.patel@vmc.gov.in',
    role: 'officer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    location: 'Vadodara Municipal Corporation',
    bio: 'Executive Engineer, Ward 7 & 8, Stormwater & Road Infrastructure.',
    points: 3100,
    badgesCount: 8,
    level: 10,
    levelTitle: 'Authorized Public Officer',
    verified: true,
    joinedDate: 'Aug 2024',
  },
  researcher: {
    id: 'usr_researcher',
    name: 'Dr. Ananya Sen',
    email: 'ananya.sen@isid.edu.in',
    role: 'researcher',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    location: 'Bengaluru, Karnataka',
    bio: 'Data Scientist & Civic Policy Researcher specializing in GIS spatial inequalities.',
    points: 4120,
    badgesCount: 11,
    level: 11,
    levelTitle: 'Lead Research Fellow',
    verified: true,
    joinedDate: 'Jan 2025',
  },
  admin: {
    id: 'usr_admin',
    name: 'JanVaani Trust & Safety Admin',
    email: 'safety@janvaani.org',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    location: 'National Command Center, New Delhi',
    bio: 'Platform integrity, content verification and government liaison administrator.',
    points: 9999,
    badgesCount: 25,
    level: 20,
    levelTitle: 'System Administrator',
    verified: true,
    joinedDate: 'Jan 2024',
  },
};

export const INITIAL_PROBLEMS: ProblemCase[] = [
  {
    id: 'JV-2026-002103',
    title: 'Waterlogging on 7th Street, Karelibaug',
    description:
      'Heavy waterlogging after every rainfall exceeding 15mm. Stormwater inlet grates are choked with construction debris and silt. The standing water (1.5 feet deep) enters ground-floor residential houses and prevents children and senior citizens from commuting safely.',
    categoryId: 'infrastructure',
    categoryName: 'Infrastructure & Roads',
    categoryIcon: 'Hammer',
    subcategoryId: 'waterlogging',
    subcategoryName: 'Waterlogging & Storm Drainage',
    location: {
      address: '7th Cross Road, Near Swaminarayan Temple, Karelibaug',
      ward: 'Ward 7',
      city: 'Vadodara',
      district: 'Vadodara',
      state: 'Gujarat',
      pincode: '390018',
      lat: 22.3255,
      lng: 73.1952,
    },
    severity: 'high',
    status: 'in_progress',
    reportedBy: {
      id: 'usr_001',
      name: 'Neha Sharma',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      role: 'Citizen Contributor',
      verified: true,
    },
    reportedAt: '2 hours ago',
    updatedAt: '30 mins ago',
    evidence: [
      {
        id: 'ev_01',
        problemId: 'JV-2026-002103',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80',
        title: 'Street Submerged in 1.5 ft Water',
        uploaderName: 'Neha Sharma',
        uploaderRole: 'Original Reporter',
        uploadedAt: '2 hours ago',
        location: '22.3255° N, 73.1952° E',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
      {
        id: 'ev_02',
        problemId: 'JV-2026-002103',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80',
        title: 'Choked Stormwater Inlet Grate',
        uploaderName: 'Amit Trivedi',
        uploaderRole: 'Resident Validator',
        uploadedAt: '1 hour ago',
        location: '22.3254° N, 73.1950° E',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
      {
        id: 'ev_03',
        problemId: 'JV-2026-002103',
        type: 'audio',
        url: '#',
        title: 'Resident Voice Testimonial (Gujarati)',
        uploaderName: 'Kishorebhai Shah',
        uploaderRole: 'Elder Resident',
        uploadedAt: '45 mins ago',
        verifiedAi: true,
      },
    ],
    affectedPopulation: 2400,
    urgencyScore: 84,
    durationDays: 14,
    previousReportsCount: 4,
    assignedAuthority: {
      agency: 'Vadodara Municipal Corporation',
      department: 'Engineering & Stormwater Drainage Dept (East Zone)',
      officer: 'Er. Rajesh K. Patel (Ward 7 In-Charge)',
      assignedAt: '1 hour ago',
      slaHoursRemaining: 18,
      slaTargetHours: 24,
      slaStatus: 'on_track',
      officialRemarks: 'Suction jetting machine dispatched. Drain de-siltation scheduled between 2 PM - 5 PM today.',
    },
    aiAnalysis: {
      summary:
        'Recurrent monsoonal waterlogging caused by obstructed stormwater catchment grates and reverse gradient flow near Karelibaug main junction. 3 duplicate reports clustered.',
      confidence: 96.4,
      duplicateClusterId: 'CLUSTER-GJ-VMC-702',
      similarCasesCount: 3,
      detectedUrgency: 'High Priority (Residential Ingress Risk)',
      routingDepartment: 'Stormwater & Road Drainage Dept, VMC',
      routingRationale:
        'Matched keywords ("waterlogging", "submerged road", "choked drain") + Geo-fenced in VMC Ward 7.',
      sentiment: 'frustrated',
      entities: ['Karelibaug', '7th Street', 'Swaminarayan Temple', 'Stormwater Drain', 'VMC Ward 7'],
      safetyEmergencyFlag: false,
    },
    timeline: [
      { step: '1', label: 'Reported & Voice Analyzed', timestamp: '2 hours ago', actor: 'Citizen (Neha Sharma)', details: 'Report filed with 2 geotagged images and audio memo.', status: 'completed' },
      { step: '2', label: 'Community Validation', timestamp: '1.5 hours ago', actor: 'Local Community (25+ residents)', details: '18 residents confirmed "I face this too". 2 added supporting photos.', status: 'completed' },
      { step: '3', label: 'AI Triage & Clustering', timestamp: '1.2 hours ago', actor: 'JanVaani AI Intel', details: 'Classified High Severity. Clustered with 3 related neighborhood reports.', status: 'completed' },
      { step: '4', label: 'Assigned to Authority', timestamp: '1 hour ago', actor: 'VMC Dispatch Engine', details: 'Auto-routed to Er. Rajesh K. Patel, Ward 7 Stormwater Dept.', status: 'completed' },
      { step: '5', label: 'Investigation & Action', timestamp: '30 mins ago', actor: 'VMC Field Team', details: 'Suction truck deployed to clean catchment chamber.', status: 'current' },
      { step: '6', label: 'Citizen Verification', timestamp: 'Pending', actor: 'Ward 7 Citizens', details: 'Post-cleanup photos will trigger citizen verification voting.', status: 'pending' },
      { step: '7', label: 'Resolution & Reward', timestamp: 'Pending', actor: 'JanVaani Reward Engine', details: '+120 pts awarded to original reporter upon successful verification.', status: 'pending' },
    ],
    civicReactions: {
      face_this_too: 25,
      witnessed: 14,
      support: 38,
      have_evidence: 6,
      can_help: 4,
      urgent: 29,
      support_solution: 12,
      dispute: 0,
      solved: 0,
    },
    userReactions: ['face_this_too', 'support'],
    commentsCount: 12,
    solutionsCount: 3,
    citizenVerification: {
      solvedVotes: 2,
      partiallySolvedVotes: 5,
      notSolvedVotes: 18,
    },
    autopsy: {
      id: 'AUT-2026-089',
      caseId: 'JV-2026-002103',
      problemTitle: 'Waterlogging on 7th Street, Karelibaug',
      resolvedOn: 'Ongoing Review',
      timeline: {
        firstReport: '14 days ago',
        escalation: '2 days ago',
        investigation: 'Today 10:00 AM',
        intervention: 'Today 11:30 AM',
        resolution: 'Scheduled',
        verification: 'Pending',
      },
      rootCause: 'Inadequate catchment pipe slope (1:400 instead of 1:200) compounded by unauthorized road asphalt overlays blocking grates.',
      processFailure: 'Pre-monsoon desilting contractor signed off inspection without lifting recessed concrete grates.',
      recurrenceRisk: 'high',
      preventionRecommendations: [
        'Replace flat cast-iron grates with raised curb-inlet side chambers to prevent debris choking.',
        'Mandate digital photo-logging of desilting depth before contractor payment sign-off.',
        'Install IoT ultrasonic water level sensor at Karelibaug junction.',
      ],
      systemicPolicyRecommendation: 'Enact municipal standard prohibiting road resurfacing that raises road level above drainage curbs.',
    },
  },
  {
    id: 'JV-2026-002104',
    title: 'Street Light Not Working on Main Sector Road',
    description:
      'A continuous stretch of 8 streetlights is completely dead for the past 6 days. The dark stretch has become dangerous for women walking from the bus stop after 8 PM.',
    categoryId: 'infrastructure',
    categoryName: 'Infrastructure & Roads',
    categoryIcon: 'Hammer',
    subcategoryId: 'street-lights',
    subcategoryName: 'Street Lights & High Masts',
    location: {
      address: 'Main Ring Road, Near GIDC Cross, Manjalpur',
      ward: 'Ward 12',
      city: 'Vadodara',
      district: 'Vadodara',
      state: 'Gujarat',
      pincode: '390011',
      lat: 22.2731,
      lng: 73.1928,
    },
    severity: 'medium',
    status: 'in_progress',
    reportedBy: {
      id: 'usr_002',
      name: 'Sunita Rao',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      role: 'Citizen Contributor',
      verified: true,
    },
    reportedAt: '4 hours ago',
    updatedAt: '1 hour ago',
    evidence: [
      {
        id: 'ev_04',
        problemId: 'JV-2026-002104',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=800&auto=format&fit=crop&q=80',
        title: 'Completely Dark Road Stretch at 9 PM',
        uploaderName: 'Sunita Rao',
        uploaderRole: 'Original Reporter',
        uploadedAt: '4 hours ago',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
    ],
    affectedPopulation: 1800,
    urgencyScore: 72,
    durationDays: 6,
    previousReportsCount: 2,
    assignedAuthority: {
      agency: 'Vadodara Municipal Corporation',
      department: 'Streetlight & Electrical Maintenance Wing',
      officer: 'S. K. Verma',
      assignedAt: '3 hours ago',
      slaHoursRemaining: 36,
      slaTargetHours: 48,
      slaStatus: 'on_track',
    },
    aiAnalysis: {
      summary: 'Feeder pillar underground cable fault detected along Manjalpur Ring Road. Night public safety risk flagged.',
      confidence: 94.8,
      similarCasesCount: 1,
      detectedUrgency: 'Medium (Night Public Safety Factor)',
      routingDepartment: 'Electrical Dept, VMC',
      routingRationale: 'Keyword "street light dead" + Ward 12 mapping.',
      sentiment: 'urgent',
      entities: ['Manjalpur', 'GIDC Cross', 'Streetlight', 'Dark spot'],
      safetyEmergencyFlag: false,
    },
    timeline: [
      { step: '1', label: 'Reported', timestamp: '4 hours ago', actor: 'Sunita Rao', details: 'Filed with night photos.', status: 'completed' },
      { step: '2', label: 'Assigned', timestamp: '3 hours ago', actor: 'Electrical Wing', details: 'Work order #EL-894 generated.', status: 'completed' },
      { step: '3', label: 'Field Inspection', timestamp: '1 hour ago', actor: 'Lineman Team', details: 'Underground cable joint burnt; replacement team en route.', status: 'current' },
    ],
    civicReactions: {
      face_this_too: 18,
      witnessed: 9,
      support: 24,
      have_evidence: 2,
      can_help: 1,
      urgent: 16,
      support_solution: 5,
      dispute: 0,
      solved: 0,
    },
    userReactions: ['support'],
    commentsCount: 7,
    solutionsCount: 2,
    citizenVerification: {
      solvedVotes: 0,
      partiallySolvedVotes: 1,
      notSolvedVotes: 8,
    },
  },
  {
    id: 'JV-2026-002105',
    title: 'Garbage not collected for 4 days near Community Park',
    description:
      'Municipal door-to-door tipper vans have not visited the residential lanes for 4 consecutive days. An open garbage mound has formed near the children park gate, attracting stray dogs and cattle.',
    categoryId: 'public-services',
    categoryName: 'Public Utilities & Sanitation',
    categoryIcon: 'Droplet',
    subcategoryId: 'garbage-dumping',
    subcategoryName: 'Garbage Collection & Dumping',
    location: {
      address: 'Lane 4, Near Gayatri Mandir, Akota',
      ward: 'Ward 9',
      city: 'Vadodara',
      district: 'Vadodara',
      state: 'Gujarat',
      pincode: '390020',
      lat: 22.2982,
      lng: 73.1764,
    },
    severity: 'high',
    status: 'submitted',
    reportedBy: {
      id: 'usr_003',
      name: 'Priya Patel',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'Civic Contributor',
      verified: true,
    },
    reportedAt: '6 hours ago',
    updatedAt: '6 hours ago',
    evidence: [
      {
        id: 'ev_05',
        problemId: 'JV-2026-002105',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=800&auto=format&fit=crop&q=80',
        title: 'Overflowing Bins and Roadside Heap',
        uploaderName: 'Priya Patel',
        uploaderRole: 'Original Reporter',
        uploadedAt: '6 hours ago',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
    ],
    affectedPopulation: 3100,
    urgencyScore: 78,
    durationDays: 4,
    previousReportsCount: 1,
    assignedAuthority: {
      agency: 'Vadodara Municipal Corporation',
      department: 'Solid Waste Management (Health Wing)',
      assignedAt: 'Pending Assignment',
      slaHoursRemaining: 24,
      slaTargetHours: 24,
      slaStatus: 'on_track',
    },
    aiAnalysis: {
      summary: 'Sanitation route failure in Akota Ward 9. Risk of disease vector transmission near primary school/park.',
      confidence: 97.1,
      similarCasesCount: 2,
      detectedUrgency: 'High Priority (Public Health Hazard)',
      routingDepartment: 'Solid Waste Management Department',
      routingRationale: 'Waste dumping & sanitation keywords detected.',
      sentiment: 'frustrated',
      entities: ['Akota', 'Gayatri Mandir', 'Garbage dump', 'Sanitation'],
      safetyEmergencyFlag: false,
    },
    timeline: [
      { step: '1', label: 'Report Submitted', timestamp: '6 hours ago', actor: 'Priya Patel', details: 'Auto-verified with high confidence image detection.', status: 'completed' },
      { step: '2', label: 'Under AI Triage', timestamp: '5 hours ago', actor: 'JanVaani Dispatcher', details: 'Forwarded to Sanitary Inspector (Ward 9).', status: 'current' },
    ],
    civicReactions: {
      face_this_too: 30,
      witnessed: 18,
      support: 44,
      have_evidence: 5,
      can_help: 2,
      urgent: 35,
      support_solution: 8,
      dispute: 0,
      solved: 0,
    },
    userReactions: ['support', 'urgent'],
    commentsCount: 14,
    solutionsCount: 1,
    citizenVerification: {
      solvedVotes: 0,
      partiallySolvedVotes: 0,
      notSolvedVotes: 22,
    },
  },
  {
    id: 'JV-2026-002106',
    title: 'Multiple Dangerous Potholes on Main Kalawad Road',
    description:
      'Over 12 deep potholes formed within a 200m stretch following heavy rains. Multiple two-wheeler riders have lost balance and suffered minor injuries during peak hours.',
    categoryId: 'infrastructure',
    categoryName: 'Infrastructure & Roads',
    categoryIcon: 'Hammer',
    subcategoryId: 'potholes',
    subcategoryName: 'Potholes & Broken Roads',
    location: {
      address: 'Opposite Crystal Mall, Kalawad Road',
      ward: 'Ward 10',
      city: 'Rajkot',
      district: 'Rajkot',
      state: 'Gujarat',
      pincode: '360005',
      lat: 22.2856,
      lng: 70.7689,
    },
    severity: 'critical',
    status: 'in_progress',
    reportedBy: {
      id: 'usr_004',
      name: 'Kabir Khan',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'Civic Validator',
      verified: true,
    },
    reportedAt: '12 hours ago',
    updatedAt: '2 hours ago',
    evidence: [
      {
        id: 'ev_06',
        problemId: 'JV-2026-002106',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80',
        title: 'Deep Crater on Fast Lane',
        uploaderName: 'Kabir Khan',
        uploaderRole: 'Original Reporter',
        uploadedAt: '12 hours ago',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
    ],
    affectedPopulation: 8500,
    urgencyScore: 92,
    durationDays: 8,
    previousReportsCount: 6,
    assignedAuthority: {
      agency: 'Rajkot Municipal Corporation',
      department: 'City Roads & Civil Works Division',
      officer: 'N. M. Joshi',
      assignedAt: '8 hours ago',
      slaHoursRemaining: 12,
      slaTargetHours: 24,
      slaStatus: 'on_track',
      officialRemarks: 'Cold mix patch material mobilized. Repair team on site.',
    },
    aiAnalysis: {
      summary: 'High crash-risk road crater cluster on arterial corridor. Immediate cold-mix / mastic asphalt patching required.',
      confidence: 98.2,
      similarCasesCount: 5,
      detectedUrgency: 'Critical (Accident & Injury Risk)',
      routingDepartment: 'Road Maintenance Wing, RMC',
      routingRationale: 'Road hazard with reported injuries.',
      sentiment: 'urgent',
      entities: ['Kalawad Road', 'Crystal Mall', 'Potholes', 'Accident risk'],
      safetyEmergencyFlag: false,
    },
    timeline: [
      { step: '1', label: 'Reported with GPS', timestamp: '12 hours ago', actor: 'Kabir Khan', details: 'High risk accident alert triggered.', status: 'completed' },
      { step: '2', label: 'Priority Escalated', timestamp: '10 hours ago', actor: 'JanVaani Priority Engine', details: 'Urgency score computed at 92/100.', status: 'completed' },
      { step: '3', label: 'Repair Crew Deployed', timestamp: '2 hours ago', actor: 'RMC Road Division', details: 'Patching work started.', status: 'current' },
    ],
    civicReactions: {
      face_this_too: 48,
      witnessed: 32,
      support: 65,
      have_evidence: 8,
      can_help: 5,
      urgent: 58,
      support_solution: 14,
      dispute: 0,
      solved: 0,
    },
    userReactions: ['witnessed', 'urgent'],
    commentsCount: 19,
    solutionsCount: 4,
    citizenVerification: {
      solvedVotes: 3,
      partiallySolvedVotes: 4,
      notSolvedVotes: 12,
    },
  },
  {
    id: 'JV-2026-002107',
    title: 'Minor leakage in Pipeline causing road erosion',
    description:
      'A continuous underground drinking water pipeline leak is seeping through the bitumen surface near Sayajigunj dairy circle, causing soft ground sinking and clean water wastage.',
    categoryId: 'public-services',
    categoryName: 'Public Utilities & Sanitation',
    categoryIcon: 'Droplet',
    subcategoryId: 'water-supply',
    subcategoryName: 'Drinking Water Shortage & Contamination',
    location: {
      address: 'Near Dairy Circle, Sayajigunj',
      ward: 'Ward 4',
      city: 'Vadodara',
      district: 'Vadodara',
      state: 'Gujarat',
      pincode: '390005',
      lat: 22.3112,
      lng: 73.1873,
    },
    severity: 'medium',
    status: 'assigned',
    reportedBy: {
      id: 'usr_005',
      name: 'Rohan Deshmukh',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      role: 'Civic Contributor',
      verified: true,
    },
    reportedAt: '1 day ago',
    updatedAt: '5 hours ago',
    evidence: [
      {
        id: 'ev_07',
        problemId: 'JV-2026-002107',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80',
        title: 'Water Seeping Through Road Asphalt',
        uploaderName: 'Rohan Deshmukh',
        uploaderRole: 'Original Reporter',
        uploadedAt: '1 day ago',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
    ],
    affectedPopulation: 1200,
    urgencyScore: 65,
    durationDays: 3,
    previousReportsCount: 1,
    assignedAuthority: {
      agency: 'Vadodara Municipal Corporation',
      department: 'Water Works & Pipeline Division',
      officer: 'B. S. Dave',
      assignedAt: '5 hours ago',
      slaHoursRemaining: 40,
      slaTargetHours: 48,
      slaStatus: 'on_track',
    },
    aiAnalysis: {
      summary: 'Treated drinking water main distribution line leakage. Risk of roadbed sinkhole formation if unaddressed.',
      confidence: 93.5,
      similarCasesCount: 0,
      detectedUrgency: 'Medium (Resource Loss + Subsidence)',
      routingDepartment: 'Water Supply Department, VMC',
      routingRationale: 'Pipeline rupture indicators matched.',
      sentiment: 'factual',
      entities: ['Sayajigunj', 'Dairy Circle', 'Water Pipeline', 'VMC Ward 4'],
      safetyEmergencyFlag: false,
    },
    timeline: [
      { step: '1', label: 'Reported', timestamp: '1 day ago', actor: 'Rohan Deshmukh', details: 'Uploaded photo evidence.', status: 'completed' },
      { step: '2', label: 'Assigned to Officer', timestamp: '5 hours ago', actor: 'VMC Water Wing', details: 'Leak repair squad scheduled for tomorrow morning.', status: 'current' },
    ],
    civicReactions: {
      face_this_too: 12,
      witnessed: 10,
      support: 19,
      have_evidence: 3,
      can_help: 1,
      urgent: 14,
      support_solution: 4,
      dispute: 0,
      solved: 0,
    },
    userReactions: [],
    commentsCount: 6,
    solutionsCount: 1,
    citizenVerification: {
      solvedVotes: 0,
      partiallySolvedVotes: 0,
      notSolvedVotes: 6,
    },
  },
  {
    id: 'JV-2026-002108',
    title: 'Open Drain causing foul smell & mosquito breeding',
    description:
      'An uncovered stormwater drainage nullah has accumulated plastic waste and stagnant black sewage, releasing toxic odors into adjoining residential flats and causing a dengue spike.',
    categoryId: 'public-services',
    categoryName: 'Public Utilities & Sanitation',
    categoryIcon: 'Droplet',
    subcategoryId: 'sewage-overflow',
    subcategoryName: 'Open Drains & Sewage Overflow',
    location: {
      address: 'Behind Railway Colony, Alkapuri',
      ward: 'Ward 6',
      city: 'Vadodara',
      district: 'Vadodara',
      state: 'Gujarat',
      pincode: '390007',
      lat: 22.3145,
      lng: 73.1798,
    },
    severity: 'high',
    status: 'in_progress',
    reportedBy: {
      id: 'usr_006',
      name: 'Manoj Bhatt',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      role: 'Civic Contributor',
      verified: true,
    },
    reportedAt: '1 day ago',
    updatedAt: '3 hours ago',
    evidence: [
      {
        id: 'ev_08',
        problemId: 'JV-2026-002108',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&auto=format&fit=crop&q=80',
        title: 'Stagnant Plastic Waste in Open Drain',
        uploaderName: 'Manoj Bhatt',
        uploaderRole: 'Original Reporter',
        uploadedAt: '1 day ago',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
    ],
    affectedPopulation: 4500,
    urgencyScore: 81,
    durationDays: 20,
    previousReportsCount: 3,
    assignedAuthority: {
      agency: 'Vadodara Municipal Corporation',
      department: 'Drainage & Vector Control Wing',
      officer: 'Dr. C. P. Solanki',
      assignedAt: '12 hours ago',
      slaHoursRemaining: 28,
      slaTargetHours: 48,
      slaStatus: 'on_track',
      officialRemarks: 'Chemical larvicide spraying completed. Excavator booked for sludge desilting on Friday.',
    },
    aiAnalysis: {
      summary: 'Public health vector hazard. High probability of mosquito larvae maturation in stagnant organic runoff.',
      confidence: 96.0,
      similarCasesCount: 4,
      detectedUrgency: 'High (Vector-borne Disease Vector Risk)',
      routingDepartment: 'Health & Vector Control Dept, VMC',
      routingRationale: 'Drain stagnation and mosquito threat.',
      sentiment: 'frustrated',
      entities: ['Alkapuri', 'Railway Colony', 'Open Nullah', 'Dengue risk'],
      safetyEmergencyFlag: false,
    },
    timeline: [
      { step: '1', label: 'Reported', timestamp: '1 day ago', actor: 'Manoj Bhatt', details: 'Verified by 18 neighbors.', status: 'completed' },
      { step: '2', label: 'Vector Fogging Executed', timestamp: '3 hours ago', actor: 'Health Dept Team', details: 'Anti-larval chemical treatment sprayed.', status: 'completed' },
      { step: '3', label: 'Desilting & Covering', timestamp: 'Pending', actor: 'Drainage Crew', details: 'Concrete slab installation proposed.', status: 'current' },
    ],
    civicReactions: {
      face_this_too: 28,
      witnessed: 15,
      support: 36,
      have_evidence: 4,
      can_help: 2,
      urgent: 31,
      support_solution: 11,
      dispute: 0,
      solved: 0,
    },
    userReactions: ['face_this_too'],
    commentsCount: 9,
    solutionsCount: 2,
    citizenVerification: {
      solvedVotes: 1,
      partiallySolvedVotes: 6,
      notSolvedVotes: 15,
    },
  },
  {
    id: 'JV-2026-002109',
    title: 'Broken Footpath & Missing Paver Blocks near Primary School',
    description:
      'Children and parents are forced to walk on the busy motor carriageway because the footpath paver blocks have caved into an abandoned telecom trench.',
    categoryId: 'infrastructure',
    categoryName: 'Infrastructure & Roads',
    categoryIcon: 'Hammer',
    subcategoryId: 'footpaths',
    subcategoryName: 'Footpaths & Pedestrian Access',
    location: {
      address: 'Near Bright Day School, VIP Road, Karelibaug',
      ward: 'Ward 7',
      city: 'Vadodara',
      district: 'Vadodara',
      state: 'Gujarat',
      pincode: '390018',
      lat: 22.3210,
      lng: 73.1995,
    },
    severity: 'medium',
    status: 'assigned',
    reportedBy: {
      id: 'usr_007',
      name: 'Farhan Sheikh',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      role: 'Civic Contributor',
      verified: true,
    },
    reportedAt: '2 days ago',
    updatedAt: '1 day ago',
    evidence: [
      {
        id: 'ev_09',
        problemId: 'JV-2026-002109',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=800&auto=format&fit=crop&q=80',
        title: 'Broken Paver Slabs Blocking School Pedestrians',
        uploaderName: 'Farhan Sheikh',
        uploaderRole: 'Original Reporter',
        uploadedAt: '2 days ago',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
    ],
    affectedPopulation: 1600,
    urgencyScore: 68,
    durationDays: 12,
    previousReportsCount: 1,
    assignedAuthority: {
      agency: 'Vadodara Municipal Corporation',
      department: 'City Civil Maintenance',
      officer: 'Er. Rajesh K. Patel',
      assignedAt: '1 day ago',
      slaHoursRemaining: 48,
      slaTargetHours: 72,
      slaStatus: 'on_track',
    },
    aiAnalysis: {
      summary: 'Pedestrian safety hazard outside school zone. Telecom trench un-reinstated.',
      confidence: 95.2,
      similarCasesCount: 1,
      detectedUrgency: 'Medium (School Zone Pedestrian Safety)',
      routingDepartment: 'Roads & Civil Maintenance, VMC',
      routingRationale: 'School boundary footpath breakdown.',
      sentiment: 'collaborative',
      entities: ['Bright Day School', 'VIP Road', 'Karelibaug', 'Footpath'],
      safetyEmergencyFlag: false,
    },
    timeline: [
      { step: '1', label: 'Reported', timestamp: '2 days ago', actor: 'Farhan Sheikh', details: 'Geotag verified.', status: 'completed' },
      { step: '2', label: 'Notice Issued to Utility', timestamp: '1 day ago', actor: 'VMC Civil Engg', details: 'Telecom agency penalized for incomplete trench reinstatement.', status: 'current' },
    ],
    civicReactions: {
      face_this_too: 15,
      witnessed: 8,
      support: 22,
      have_evidence: 2,
      can_help: 3,
      urgent: 12,
      support_solution: 6,
      dispute: 0,
      solved: 0,
    },
    userReactions: [],
    commentsCount: 8,
    solutionsCount: 2,
    citizenVerification: {
      solvedVotes: 0,
      partiallySolvedVotes: 2,
      notSolvedVotes: 10,
    },
  },
  {
    id: 'JV-2026-002110',
    title: 'Dangling Live High-Voltage Cable outside Sabzi Mandi',
    description:
      'Storm winds dislodged an overhead 440V distribution cable. It is dangling at head height (6 feet) directly above the entrance of the crowded evening vegetable market.',
    categoryId: 'infrastructure',
    categoryName: 'Infrastructure & Roads',
    categoryIcon: 'Hammer',
    subcategoryId: 'electricity-cuts',
    subcategoryName: 'Power Cuts & Voltage Fluctuations',
    location: {
      address: 'Main Gate, Sabzi Mandi, Khanderao Market Area',
      ward: 'Ward 2',
      city: 'Vadodara',
      district: 'Vadodara',
      state: 'Gujarat',
      pincode: '390001',
      lat: 22.2965,
      lng: 73.2084,
    },
    severity: 'critical',
    status: 'in_progress',
    reportedBy: {
      id: 'usr_008',
      name: 'Deepak Varma',
      avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
      role: 'Civic Contributor',
      verified: true,
    },
    reportedAt: '45 mins ago',
    updatedAt: '10 mins ago',
    evidence: [
      {
        id: 'ev_10',
        problemId: 'JV-2026-002110',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b6?w=800&auto=format&fit=crop&q=80',
        title: 'Hanging Live Cable Over Mandi Entry',
        uploaderName: 'Deepak Varma',
        uploaderRole: 'Original Reporter',
        uploadedAt: '45 mins ago',
        verifiedAi: true,
        tamperCheck: 'passed',
      },
    ],
    affectedPopulation: 6200,
    urgencyScore: 98,
    durationDays: 1,
    previousReportsCount: 0,
    assignedAuthority: {
      agency: 'Madhya Gujarat Vij Company Ltd (MGVCL)',
      department: 'Emergency Breakdown Squad (City Circle)',
      officer: 'Junior Engineer T. N. Pandya',
      assignedAt: '30 mins ago',
      slaHoursRemaining: 2,
      slaTargetHours: 4,
      slaStatus: 'on_track',
      officialRemarks: 'Feeder isolated from substation. Rapid repair crew on site with ladder truck.',
    },
    aiAnalysis: {
      summary: 'CRITICAL ELECTROCUTION HAZARD. High footfall public market area. Substation auto-isolation initiated.',
      confidence: 99.1,
      similarCasesCount: 0,
      detectedUrgency: 'CRITICAL EMERGENCY (Immediate Life Safety Threat)',
      routingDepartment: 'MGVCL Electricity Emergency Response',
      routingRationale: 'Live powerline hazard in market.',
      sentiment: 'urgent',
      entities: ['Sabzi Mandi', 'Khanderao Market', '440V Wire', 'MGVCL'],
      safetyEmergencyFlag: true,
    },
    timeline: [
      { step: '1', label: 'Emergency SOS Alert', timestamp: '45 mins ago', actor: 'Deepak Varma', details: 'Classified immediate threat.', status: 'completed' },
      { step: '2', label: 'Substation Feeder Tripped', timestamp: '35 mins ago', actor: 'MGVCL SCADA Control', details: 'Power cut to circuit to prevent injury.', status: 'completed' },
      { step: '3', label: 'Emergency Van On Site', timestamp: '10 mins ago', actor: 'MGVCL Line Squad', details: 'Rewiring insulator brackets.', status: 'current' },
    ],
    civicReactions: {
      face_this_too: 42,
      witnessed: 29,
      support: 51,
      have_evidence: 7,
      can_help: 8,
      urgent: 85,
      support_solution: 10,
      dispute: 0,
      solved: 0,
    },
    userReactions: ['urgent', 'witnessed'],
    commentsCount: 19,
    solutionsCount: 2,
    citizenVerification: {
      solvedVotes: 4,
      partiallySolvedVotes: 1,
      notSolvedVotes: 5,
    },
  },
];

export const INITIAL_SOLUTIONS: Solution[] = [
  {
    id: 'SOL-2026-101',
    problemId: 'JV-2026-002103',
    problemTitle: 'Waterlogging on 7th Street, Karelibaug',
    problemLocation: 'Karelibaug, Vadodara',
    title: 'Modular Dual-Chamber Sump with Silt Trap & Raised Curb Inlets',
    summary:
      'Install precast reinforced concrete catchment chambers with removable heavy-duty galvanized silt-trapping baskets. Upgrades the gravity drainage gradient and prevents asphalt runoff from clogging the underground trunk line.',
    author: {
      id: 'usr_sol_01',
      name: 'Er. Rohan Mehta',
      role: 'expert',
      title: 'Senior Civil & Drainage Engineer (Chartered)',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      verified: true,
      organization: 'Civic Infrastructure Research Group',
    },
    submittedAt: '1 day ago',
    expectedImpact: 'Eliminates 90% standing water within 15 minutes of rainfall. Reduces siltation by 85%.',
    estimatedCost: '₹1,80,000 (3 junction pits)',
    implementationTime: '5 Days (Off-peak night installation)',
    feasibilityScore: 92,
    upvotes: 128,
    commentsCount: 18,
    keySteps: [
      'Excavate 3 existing flat grates and install 1.2m deep precast dual-chamber silt pits.',
      'Connect overflow pipe directly to 600mm Karelibaug trunk drain with 1:150 slope.',
      'Fit removable hot-dip galvanized mesh baskets for zero-machine municipal de-silting.',
      'Re-level road asphalt lip by 25mm to create natural drainage slope towards curb inlets.',
    ],
    killCriticAnalysis: {
      confidenceScore: 88,
      critique:
        'Technically sound engineering solution utilizing precast modular components. Highly suitable for dense urban alleys where heavy machinery cannot operate.',
      assumptionsChallenged: [
        'Assumes downstream 600mm trunk drain is not simultaneously surcharged during peak monsoon.',
        'Assumes municipal sanitation staff will regularly empty silt collection baskets twice a month.',
      ],
      unintendedConsequences: [
        'If baskets are neglected for >60 days, organic decomposition will cause localized odors.',
        'High initial procurement cost compared to traditional single-grate brick masonry.',
      ],
      validationRequirements: [
        'Verify hydraulic invert levels of the Karelibaug trunk sewer during heavy storm simulation.',
        'Obtain municipal sanitation department written agreement for scheduled basket clearing.',
      ],
    },
    status: 'accepted',
    userUpvoted: true,
  },
  {
    id: 'SOL-2026-102',
    problemId: 'JV-2026-002105',
    problemTitle: 'Garbage not collected for 4 days near Community Park',
    problemLocation: 'Akota, Vadodara',
    title: 'Smart Solar-Powered IoT Fill-Level Sensor & Dynamic Route Optimization',
    summary:
      'Deploy low-cost ultrasonic fill-level sensors inside municipal bulk bins paired with automated SMS dispatches to the nearest zonal tipper van when bins cross 75% capacity.',
    author: {
      id: 'usr_sol_02',
      name: 'Students Team - CleanTech Gujarat',
      role: 'student',
      title: 'Final Year IoT & CS Engineering Students',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      verified: true,
      organization: 'MS University Faculty of Tech',
    },
    submittedAt: '2 days ago',
    expectedImpact: 'Prevents 100% bin overflows. Optimizes fuel consumption by 22% via dynamic routing.',
    estimatedCost: '₹3,500 per bin sensor + open-source dashboard',
    implementationTime: '2 Weeks pilot in Ward 9',
    feasibilityScore: 86,
    upvotes: 94,
    commentsCount: 12,
    keySteps: [
      'Install IP68 rated weatherproof ultrasonic distance sensor on bin inner lid.',
      'Connect via LoRaWAN/NB-IoT to JanVaani Civic API gateway.',
      'Trigger automated dispatch alerts to Ward Sanitary Inspector when capacity hits 75%.',
    ],
    killCriticAnalysis: {
      confidenceScore: 82,
      critique:
        'Strong technology intervention addressing municipal driver route evasion and irregular collection cycles.',
      assumptionsChallenged: [
        'Sensors may get damaged or stolen if not physically enclosed in vandal-proof metal casing.',
        'Requires reliable GSM/LoRa connectivity in shaded park alleys.',
      ],
      unintendedConsequences: [
        'Drivers may prioritize sensor bins over un-sensored small roadside bins.',
      ],
      validationRequirements: [
        'Run 30-day physical pilot in 10 Akota bins to measure false positives caused by bulky cardboard.',
      ],
    },
    status: 'under_review',
    userUpvoted: false,
  },
  {
    id: 'SOL-2026-103',
    problemId: 'JV-2026-002104',
    problemTitle: 'Street Light Not Working on Main Sector Road',
    problemLocation: 'Manjalpur, Vadodara',
    title: 'Community-Adopted Solar Micro-Grid LED Mast with Smart Ambient Dimming',
    summary:
      'Decentralized solar street lighting with lithium-ferro-phosphate (LiFePO4) battery packs mounted at 7m height, eliminating dependence on faulty underground cable feeder lines.',
    author: {
      id: 'usr_sol_03',
      name: 'SunPower Civic NGO',
      role: 'organization',
      title: 'Renewable Urban Energy Initiative',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      verified: true,
      organization: 'Vadodara Green Alliance',
    },
    submittedAt: '3 days ago',
    expectedImpact: 'Zero night blackouts. 100% carbon-neutral lighting with 12-hour continuous backup.',
    estimatedCost: '₹14,000 per pole',
    implementationTime: '1 Week',
    feasibilityScore: 89,
    upvotes: 76,
    commentsCount: 9,
    keySteps: [
      'Mount 60W monocrystalline solar panel and integrated 40W LED fixture.',
      'Program automatic dusk-to-dawn sensor with 100% brightness until midnight, 50% till dawn.',
    ],
    killCriticAnalysis: {
      confidenceScore: 85,
      critique: 'Practical off-grid solution that bypasses slow municipal underground cable excavations.',
      assumptionsChallenged: ['Monsoon sunlight drop may reduce battery backup to 6 hours if consecutive rainy days occur.'],
      unintendedConsequences: ['Dust accumulation on solar panels in dry seasons reduces efficiency by 20% without cleaning.'],
      validationRequirements: ['Ensure minimum 3-day rainy autonomy battery sizing.'],
    },
    status: 'under_review',
    userUpvoted: false,
  },
];

export const INITIAL_COMMUNITIES: Community[] = [
  {
    id: 'comm_01',
    name: 'Vadodara Civic Issues',
    slug: 'vadodara-civic-issues',
    description: 'Active forum for citizens, RWAs, students and engineers to discuss, report, and solve municipal challenges across all 19 wards of Vadodara.',
    banner: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=150&auto=format&fit=crop&q=80',
    category: 'City Hub',
    location: 'Vadodara, Gujarat',
    membersCount: 2640,
    problemsCount: 420,
    solutionsCount: 180,
    moderators: ['Neha Sharma', 'Er. Rajesh Patel', 'Manoj Bhatt'],
    trending: true,
    joined: true,
  },
  {
    id: 'comm_02',
    name: 'Students for Better India',
    slug: 'students-for-better-india',
    description: 'A nationwide collegiate network of engineering, architecture, law and public policy students turning civic grievances into innovative semester projects.',
    banner: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'Students & Innovation',
    location: 'All India',
    membersCount: 5120,
    problemsCount: 890,
    solutionsCount: 340,
    moderators: ['Aarav Joshi', 'Priya K.', 'Dev Mehta'],
    trending: true,
    joined: true,
  },
  {
    id: 'comm_03',
    name: 'Environment & Lake Protectors',
    slug: 'environment-lovers',
    description: 'Dedicated to preserving urban water bodies, checking toxic industrial discharge, preventing illegal tree cutting, and advocating for urban wetlands.',
    banner: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=150&auto=format&fit=crop&q=80',
    category: 'Environment',
    location: 'Gujarat & Western India',
    membersCount: 3210,
    problemsCount: 210,
    solutionsCount: 115,
    moderators: ['Dr. Vikram Shah', 'Sunita Rao'],
    trending: false,
    joined: false,
  },
  {
    id: 'comm_04',
    name: 'Urban Mobility & Safe Roads',
    slug: 'urban-mobility-forum',
    description: 'Advocating for pedestrian safety, dignified footpaths, synchronized traffic signals, safe school zones, and cycle tracks.',
    banner: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=150&auto=format&fit=crop&q=80',
    category: 'Transportation',
    location: 'Western Zone',
    membersCount: 1840,
    problemsCount: 140,
    solutionsCount: 65,
    moderators: ['Kabir Khan', 'Farhan Sheikh'],
    trending: false,
    joined: false,
  },
];

export const INITIAL_BOUNTIES: Bounty[] = [
  {
    id: 'BOUNTY-2026-01',
    title: 'Smart Waste Management Solution for High-Density Markets',
    organization: 'Clean India Foundation & VMC',
    orgLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    problemTitle: 'Garbage accumulation around wholesale fruit & vegetable mandis',
    location: 'Vadodara & Ahmedabad',
    rewardAmount: 25000,
    currency: '₹',
    deadline: '15 Sept 2026',
    daysLeft: 20,
    participantsCount: 126,
    category: 'Sanitation & Clean Energy',
    description:
      'Design a decentralized organic waste processing or collection system that converts wet vegetable waste generated in daily markets into compost or biogas within 24 hours, preventing roadside decay.',
    requirements: [
      'Low spatial footprint (< 150 sq ft).',
      'Operational without foul odor leakage in crowded retail zones.',
      'CapEx cost model under ₹2,50,000.',
      'Community or cooperative revenue model for sanitation workers.',
    ],
    judgingCriteria: [
      'Feasibility & Scalability (35%)',
      'Cost Effectiveness & ROI (25%)',
      'KillCritic Red-Team Score (20%)',
      'Citizen & Worker Adoption (20%)',
    ],
    status: 'active',
  },
  {
    id: 'BOUNTY-2026-02',
    title: 'Water Conservation & Leak Detection Sensor Challenge',
    organization: 'Gujarat Urban Innovation Mission',
    orgLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80',
    problemTitle: 'Underground pipeline leakages causing 30% Non-Revenue Water (NRW) loss',
    location: 'Statewide Gujarat',
    rewardAmount: 50000,
    currency: '₹',
    deadline: '10 Oct 2026',
    daysLeft: 45,
    participantsCount: 85,
    category: 'Water & Utilities',
    description:
      'Develop an acoustic or pressure-differential IoT sensor node that clamps onto existing ductile iron / PVC municipal pipelines to pinpoint hidden leaks before road cave-ins happen.',
    requirements: [
      'Battery life > 2 years on coin/solar cell.',
      'Telemetry over NB-IoT or LoRaWAN to JanVaani Open GIS API.',
      'Pinpoint leak within ± 3 meters.',
    ],
    judgingCriteria: [
      'Accuracy & Detection Limit (40%)',
      'Hardware Cost & Longevity (30%)',
      'Ease of Non-Invasive Retrofit (30%)',
    ],
    status: 'active',
  },
  {
    id: 'BOUNTY-2026-03',
    title: 'Traffic Decongestion Plan for Old City Heritage Corridors',
    organization: 'Urban Mobility Trust & Traffic Police',
    orgLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    problemTitle: 'Extreme gridlock on Mandvi to Panigate heritage stretch',
    location: 'Vadodara Old City',
    rewardAmount: 75000,
    currency: '₹',
    deadline: '25 Oct 2026',
    daysLeft: 60,
    participantsCount: 95,
    category: 'Urban Mobility',
    description:
      'Produce an evidence-backed pedestrianization, one-way circulation, and micro-parking plan that increases pedestrian throughput while preserving local shopkeeper loading/unloading logistics.',
    requirements: [
      'Peak hour traffic counts & origin-destination survey data.',
      'Simulation video / GIS map of revised flow.',
      'Shopkeeper consensus strategy.',
    ],
    judgingCriteria: [
      'Traffic Simulation Rigor (40%)',
      'Stakeholder Inclusivity (30%)',
      'Implementation Feasibility within 60 days (30%)',
    ],
    status: 'active',
  },
];

export const TOP_CONTRIBUTORS: TopContributor[] = [
  {
    id: 'usr_001',
    rank: 1,
    name: 'Neha Sharma',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    location: 'Vadodara, Gujarat',
    role: 'Civic Champion',
    points: 4680,
    badgesCount: 12,
    problemsReported: 34,
    verificationsCount: 82,
    solutionsCount: 8,
  },
  {
    id: 'usr_004',
    rank: 2,
    name: 'Kabir Khan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    location: 'Mumbai, Maharashtra',
    role: 'Evidence Master',
    points: 3420,
    badgesCount: 9,
    problemsReported: 28,
    verificationsCount: 65,
    solutionsCount: 5,
  },
  {
    id: 'usr_003',
    rank: 3,
    name: 'Priya Patel',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    location: 'Vadodara, Gujarat',
    role: 'Community Validator',
    points: 2890,
    badgesCount: 8,
    problemsReported: 22,
    verificationsCount: 54,
    solutionsCount: 4,
  },
  {
    id: 'usr_student',
    rank: 4,
    name: 'Aarav Joshi',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    location: 'Ahmedabad, Gujarat',
    role: 'Solution Builder',
    points: 2450,
    badgesCount: 7,
    problemsReported: 16,
    verificationsCount: 42,
    solutionsCount: 9,
  },
  {
    id: 'usr_009',
    rank: 5,
    name: 'Riya Mehta',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    location: 'Bengaluru, Karnataka',
    role: 'Research Contributor',
    points: 2210,
    badgesCount: 6,
    problemsReported: 14,
    verificationsCount: 39,
    solutionsCount: 6,
  },
];

export const CIVIC_BADGES: CivicBadge[] = [
  {
    id: 'badge_01',
    name: 'First Contributor',
    description: 'Reported your first verified civic problem with geotagged evidence.',
    icon: 'Sparkles',
    tier: 'bronze',
    category: 'Discovery',
    earnedDate: '12 Jan 2025',
    unlocked: true,
  },
  {
    id: 'badge_02',
    name: 'Evidence Builder',
    description: 'Uploaded 10+ high-definition photos, videos, or audio testimonials verified by AI.',
    icon: 'Camera',
    tier: 'silver',
    category: 'Evidence',
    earnedDate: '28 Jan 2025',
    unlocked: true,
  },
  {
    id: 'badge_03',
    name: 'Community Validator',
    description: 'Independently confirmed or inspected 25+ neighborhood civic reports.',
    icon: 'CheckCircle2',
    tier: 'silver',
    category: 'Verification',
    earnedDate: '15 Feb 2025',
    unlocked: true,
  },
  {
    id: 'badge_04',
    name: 'Solution Builder',
    description: 'Submitted an engineering or community solution that reached the Top 3 in KillCritic scoring.',
    icon: 'Lightbulb',
    tier: 'gold',
    category: 'Solutions',
    earnedDate: '02 Mar 2025',
    unlocked: true,
  },
  {
    id: 'badge_05',
    name: 'Civic Champion',
    description: 'Achieved Level 10+ with over 5 confirmed resolved problems in your municipality.',
    icon: 'Award',
    tier: 'platinum',
    category: 'Impact',
    earnedDate: '20 Mar 2025',
    unlocked: true,
  },
  {
    id: 'badge_06',
    name: 'Red-Team Critic',
    description: 'Participated in KillCritic solution stress-testing by identifying hidden engineering risks.',
    icon: 'ShieldCheck',
    tier: 'gold',
    category: 'Intelligence',
    unlocked: false,
  },
];

export const GOVERNMENT_DEPARTMENTS: GovernmentDepartment[] = [
  {
    id: 'dept_pwd',
    name: 'Public Works & Roads Department',
    code: 'PWD-ROADS',
    headOfficer: 'Chief Engineer M. R. Vyas',
    totalCases: 1256,
    newCases: 42,
    inProgressCases: 432,
    resolvedCases: 782,
    overdueCases: 42,
    avgResolutionHours: 38,
    slaRate: 92.4,
    budgetUtilized: '₹4.8 Cr / ₹6.2 Cr',
  },
  {
    id: 'dept_swm',
    name: 'Solid Waste & Sanitation Department',
    code: 'SWM-HEALTH',
    headOfficer: 'Health Officer Dr. R. K. Bhatt',
    totalCases: 1450,
    newCases: 65,
    inProgressCases: 210,
    resolvedCases: 1175,
    overdueCases: 28,
    avgResolutionHours: 22,
    slaRate: 94.8,
    budgetUtilized: '₹3.2 Cr / ₹3.8 Cr',
  },
  {
    id: 'dept_drainage',
    name: 'Stormwater Drainage & Flood Mitigation',
    code: 'SWD-DRAIN',
    headOfficer: 'Er. Rajesh K. Patel',
    totalCases: 890,
    newCases: 38,
    inProgressCases: 310,
    resolvedCases: 542,
    overdueCases: 36,
    avgResolutionHours: 44,
    slaRate: 88.6,
    budgetUtilized: '₹2.9 Cr / ₹4.0 Cr',
  },
  {
    id: 'dept_electrical',
    name: 'Street Lighting & Electrical Wing',
    code: 'ELEC-LGT',
    headOfficer: 'Er. S. K. Verma',
    totalCases: 680,
    newCases: 15,
    inProgressCases: 95,
    resolvedCases: 570,
    overdueCases: 12,
    avgResolutionHours: 19,
    slaRate: 96.2,
    budgetUtilized: '₹1.4 Cr / ₹1.8 Cr',
  },
  {
    id: 'dept_water',
    name: 'Water Supply & Pipeline Distribution',
    code: 'WTR-DIST',
    headOfficer: 'Er. B. S. Dave',
    totalCases: 1120,
    newCases: 28,
    inProgressCases: 280,
    resolvedCases: 812,
    overdueCases: 26,
    avgResolutionHours: 31,
    slaRate: 91.0,
    budgetUtilized: '₹3.6 Cr / ₹4.5 Cr',
  },
];

export const RESEARCH_DATASETS: ResearchDataset[] = [
  {
    id: 'ds_01',
    title: 'Urban Infrastructure Grievance Density & Resolution Latency (Vadodara)',
    description: 'Anonymized, privacy-preserving geospatial records of 128,000+ citizen problem cases mapped to ward boundaries, category taxonomy, and response SLA intervals.',
    category: 'Urban Planning',
    recordsCount: 128450,
    geographicScope: 'Vadodara Municipal Corporation (19 Wards)',
    timeRange: 'Jan 2025 - Present',
    privacyMeasures: ['500m Lat/Lng Spatial Fuzzing', 'PII Stripping', 'Differential Privacy ε=0.5'],
    downloadFormats: ['GeoJSON', 'CSV', 'Parquet'],
    sizeMb: 42.5,
    lastUpdated: 'August 2026',
  },
  {
    id: 'ds_02',
    title: 'Monsoon Waterlogging & Drainage Blockage Recurrence Index',
    description: 'Clustered geospatial dataset correlating local elevation depressions, rainfall intensity mm/hr, and verified citizen waterlogging reports across 6 Tier-2 Indian cities.',
    category: 'Climate & Hydrology',
    recordsCount: 480200,
    geographicScope: 'Western India (Vadodara, Surat, Rajkot, Pune, Nashik, Indore)',
    timeRange: 'Monsoon 2024 - 2026',
    privacyMeasures: ['Aggregated 100m Grid', 'No Citizen Identifiers'],
    downloadFormats: ['GeoJSON', 'NetCDF', 'CSV'],
    sizeMb: 89.2,
    lastUpdated: 'July 2026',
  },
  {
    id: 'ds_03',
    title: 'Night Streetlighting Dark Spots & Pedestrian Mobility Safety Corridors',
    description: 'Night visibility report points, streetlight breakdown repair timelines, and evening pedestrian footfall indices.',
    category: 'Public Safety',
    recordsCount: 95400,
    geographicScope: 'Multi-City Dataset',
    timeRange: 'Q1-Q3 2026',
    privacyMeasures: ['K-Anonymity (k=10)', 'Temporal Jittering ±2 hours'],
    downloadFormats: ['CSV', 'Shapefile'],
    sizeMb: 28.1,
    lastUpdated: 'August 2026',
  },
];

export const POLICY_INSIGHTS: PolicyInsightItem[] = [
  {
    id: 'POL-2026-01',
    title: 'Surge in Monsoon Urban Drainage Blockages due to Construction Debris Dumping',
    region: 'Vadodara & Ahmedabad Corridors',
    category: 'Infrastructure & Storm Drainage',
    observedData: '65% spike in waterlogging reports in newly developing suburban wards within 15 mins of >10mm rainfall.',
    aiInference: 'Post-construction road curb reinstatement compliance dropped from 84% to 41% across private commercial building developments.',
    hypothesis: 'Private developers dumping excavation silt into open stormwater nullahs to save disposal cartage fees.',
    policyRecommendation: 'Institute a mandatory ₹50,000 refundable environmental escrow on all municipal building plan approvals, released only after drone inspection of adjoining stormwater drains.',
    impactScore: 94,
    urgency: 'critical',
    confidence: 96.8,
  },
  {
    id: 'POL-2026-02',
    title: 'Frequent Streetlight Circuit Tripping along Industrial GIDC Belts',
    region: 'Manjalpur & Makarpura GIDC',
    category: 'Electrical Utilities',
    observedData: 'Average streetlight dark-time duration increased from 18 hours to 42 hours during unseasonal thunderstorms.',
    aiInference: 'Underground cables laid during 2018 have reached end-of-life insulation resistance thresholds.',
    hypothesis: 'High soil acidity and chemical runoff in industrial zones accelerates PVC insulation brittleness.',
    policyRecommendation: 'Upgrade future cable specifications to XLPE armored cables with cathodic soil protection in all municipal GIDC border wards.',
    impactScore: 82,
    urgency: 'high',
    confidence: 91.2,
  },
];

export const AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'LOG-9921',
    timestamp: '10 mins ago',
    actor: 'Er. Rajesh K. Patel',
    actorRole: 'Authorized Public Officer',
    action: 'STATUS_UPDATE_IN_PROGRESS',
    target: 'JV-2026-002103 (Karelibaug Waterlogging)',
    ipAddress: '117.240.18.94 (Govt NIC Intranet)',
    status: 'success',
    details: 'Dispatched suction jetting unit #VMC-SJ-04. SLA countdown active.',
  },
  {
    id: 'LOG-9920',
    timestamp: '35 mins ago',
    actor: 'MGVCL SCADA Auto-Agent',
    actorRole: 'Utility Integration Bot',
    action: 'EMERGENCY_FEEDER_TRIP',
    target: 'JV-2026-002110 (Khanderao Market Cable)',
    ipAddress: '10.20.104.12 (SCADA API Gateway)',
    status: 'success',
    details: 'Feeder #02 isolated within 420ms of emergency report confirmation.',
  },
  {
    id: 'LOG-9919',
    timestamp: '1 hour ago',
    actor: 'JanVaani AI Guardrail',
    actorRole: 'Platform AI Classifier',
    action: 'TAMPER_DETECTION_PASS',
    target: 'EV_02 (Inlet Grate Evidence Photo)',
    ipAddress: 'Internal Worker Node #07',
    status: 'success',
    details: 'Exif metadata matches GPS coords 22.3254, 73.1950. No generative AI or copy-paste artifacts detected.',
  },
];
